### ISSUE TITLE
Some tests are failing on ARM architectures | AssertionErrors

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#21]
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /builds/firefly-cpp/aports/testing/py3-niaarm/src/niaarm-0.1.2
collected 21 items
niaarm/tests/test_coverage.py ..                                         [  9%]
niaarm/tests/test_cut_point.py ...                                       [ 23%]
niaarm/tests/test_read_csv.py FF                                         [ 33%]
niaarm/tests/test_rule_building.py F..F.....                             [ 76%]
niaarm/tests/test_shrinkage.py FF.                                       [ 90%]
niaarm/tests/test_support_confidence.py FF                               [100%]
=================================== FAILURES ===================================
____________________ TestReadCSVAbalone.test_read_features _____________________
self = <niaarm.tests.test_read_csv.TestReadCSVAbalone testMethod=test_read_features>
    def test_read_features(self):
    
        header = [
            'Sex',
            'Length',
            'Diameter',
            'Height',
            'Whole weight',
            'Shucked weight',
            'Viscera weight',
            'Shell weight',
            'Rings']
        minval = [None, 0.075, 0.055, 0.0, 0.002, 0.001, 0.0005, 0.0015, 1]
        maxval = [None, 0.815, 0.65, 1.13, 2.8255, 1.488, 0.76, 1.005, 29]
        dtypes_a = [
            'cat',
            'float',
            'float',
            'float',
            'float',
            'float',
            'float',
            'float',
            'int']
    
        data = Dataset(os.path.join(os.path.dirname(__file__), 'test_data', 'Abalone.csv'))
    
        features = data.features
    
        individual = data.dimension
    
        header_a = data.header
    
        min_value = []
        max_value = []
        dtypes = []
    
        for i in range(len(features)):
            min_value.append(features[i].min_val)
            max_value.append(features[i].max_val)
            dtypes.append(features[i].dtype)
    
        self.assertEqual(len(features), 9)
>       self.assertEqual(individual, 36)
E       AssertionError: 35 != 36
niaarm/tests/test_read_csv.py:50: AssertionError
______________________ TestReadCSVWiki.test_read_features ______________________
self = <niaarm.tests.test_read_csv.TestReadCSVWiki testMethod=test_read_features>
    def test_read_features(self):
        header = ['Feat1', 'Feat2']
        minval = [None, 0]
        maxval = [None, 1]
        dtypes_a = ['cat', 'int']
    
        data = Dataset(os.path.join(os.path.dirname(__file__), 'test_data', 'wiki_test_case.csv'))
    
        features = data.features
    
        individual = data.dimension
    
        header_a = data.header
    
        min_value = []
        max_value = []
        dtypes = []
        categories = []
    
        for i in range(len(features)):
            min_value.append(features[i].min_val)
            max_value.append(features[i].max_val)
            dtypes.append(features[i].dtype)
            categories.append(features[i].categories)
    
        self.assertEqual(len(features), 2)
>       self.assertEqual(individual, 8)
E       AssertionError: 7 != 8
niaarm/tests/test_read_csv.py:84: AssertionError
________________________ TestBuildRuleA.test_build_rule ________________________
self = <niaarm.tests.test_rule_building.TestBuildRuleA testMethod=test_build_rule>
    def test_build_rule(self):
        """Test procedure for building rules"""
        rule1 = self.oper.build_rule([0.45328107,
                                      0.13655004,
                                      0.6860223,
                                      0.78527931,
                                      0.96291945,
                                      0.18117294,
                                      0.50567635])
        rule2 = self.oper.build_rule([0.95328107,
                                      0.13655004,
                                      0.6860223,
                                      0.78527931,
                                      0.96291945,
                                      0.18117294,
                                      0.50567635])
        rule3 = self.oper.build_rule([0.95328107,
                                      0.98655004,
                                      0.6860223,
                                      0.78527931,
                                      0.96291945,
                                      0.18117294,
                                      0.50567635])
        rule4 = self.oper.build_rule([0.45328107,
                                      0.20655004,
                                      0.6860223,
                                      0.78527931,
                                      0.10291945,
                                      0.18117294,
                                      0.50567635])
        rule5 = self.oper.build_rule([0.45328107,
                                      0.20655004,
                                      0.2060223,
                                      0.79527931,
                                      0.10291945,
                                      0.18117294,
                                      0.50567635])
        rule6 = self.oper.build_rule([0.45328107,
                                      0.20655004,
                                      0.2060223,
                                      0.19727931,
                                      0.10291945,
                                      0.18117294,
                                      0.50567635])
        rule7 = self.oper.build_rule([0.95328107,
                                      0.20655004,
                                      0.2060223,
                                      0.19727931,
                                      0.10291945,
                                      0.18117294,
                                      0.50567635])
    
        self.assertEqual(rule1, [["A"], "NO"])
        self.assertEqual(rule2, [["B"], "NO"])
        self.assertEqual(rule3, ["NO", "NO"])
>       self.assertEqual(rule4, [["A"], [1, 1]])
E       AssertionError: Lists differ: [['A'], 'NO'] != [['A'], [1, 1]]
E       
E       First differing element 1:
E       'NO'
E       [1, 1]
E       
E       - [['A'], 'NO']
E       + [['A'], [1, 1]]
niaarm/tests/test_rule_building.py:134: AssertionError
______________________ TestBuildRuleA.test_threshold_move ______________________
self = <niaarm.tests.test_rule_building.TestBuildRuleA testMethod=test_threshold_move>
    def test_threshold_move(self):
        move = self.oper.threshold_move(0)
        move2 = self.oper.threshold_move(1)
    
        self.assertEqual(move, 1)
>       self.assertEqual(move2, 2)
E       AssertionError: 1 != 2
niaarm/tests/test_rule_building.py:65: AssertionError
____________________________ TestShrinkageA.test_A _____________________________
self = <niaarm.tests.test_shrinkage.TestShrinkageA testMethod=test_A>
    def test_A(self):
        # Rule: A => 0
        vector = [
            0.27989089,
            0.10,
            0.28412449,
            0.25629334,
            0.0796189,
            0.0,
            0.0]
    
        oper = AssociationRule(self.features)
    
        cut = _cut_point(0, len(self.features))
    
        rule = oper.build_rule(vector)
    
        antecedent = rule[:cut]
        consequent = rule[cut:]
    
        shrinkage = oper.shrinkage(antecedent, consequent)
    
>       self.assertEqual(shrinkage, 1)
E       AssertionError: 0.0 != 1
niaarm/tests/test_shrinkage.py:35: AssertionError
____________________________ TestShrinkageA.test_B _____________________________
self = <niaarm.tests.test_shrinkage.TestShrinkageA testMethod=test_B>
    def test_B(self):
        vector = [
            0.95157038,
            0.17362622,
            0.8,
            0.84473467,
            0.15286096,
            0.22928163,
            0.68833485]
    
        oper = AssociationRule(self.features)
    
        cut = _cut_point(0, len(self.features))
    
        rule = oper.build_rule(vector)
    
        antecedent = rule[:cut]
        consequent = rule[cut:]
    
        shrinkage = oper.shrinkage(antecedent, consequent)
    
>       self.assertEqual(shrinkage, 1)
E       AssertionError: 0.0 != 1
niaarm/tests/test_shrinkage.py:58: AssertionError
_________________________ TestSupportConfidence.test_B _________________________
self = <niaarm.tests.test_support_confidence.TestSupportConfidence testMethod=test_B>
    def test_B(self):
        # Rule: B => 1
        antecedent_b = [['B']]
    
        consequent_b = [[1, 1]]
    
        support_b = 0.2857142857142857
    
        confidence_b = 0.666666666667
    
        vector = [
            0.95157038,
            0.17362622,
            0.8,
            0.84473467,
            0.15286096,
            0.22928163,
            0.68833485]
    
        oper = AssociationRule(self.features)
    
        cut = _cut_point(0, len(self.features))
    
        rule = oper.build_rule(vector)
    
        antecedent = rule[:cut]
        consequent = rule[cut:]
    
        support, confidence = oper.support_confidence(
            antecedent, consequent, self.transactions)
    
        self.assertEqual(antecedent, antecedent_b)
>       self.assertEqual(consequent, consequent_b)
E       AssertionError: Lists differ: ['NO'] != [[1, 1]]
E       
E       First differing element 0:
E       'NO'
E       [1, 1]
E       
E       - ['NO']
E       + [[1, 1]]
niaarm/tests/test_support_confidence.py:84: AssertionError
_________________________ TestSupportConfidence.test_a _________________________
self = <niaarm.tests.test_support_confidence.TestSupportConfidence testMethod=test_a>
    def test_a(self):
        # Rule: A => 0
        antecedent_a = [['A']]
    
        consequent_a = [[0, 0]]
    
        support_a = 0.42857142857142855
    
        confidence_a = 0.75
    
        vector = [
            0.27989089,
            0.10,
            0.28412449,
            0.25629334,
            0.0796189,
            0.0,
            0.0]
    
        oper = AssociationRule(self.features)
    
        cut = _cut_point(0, len(self.features))
    
        rule = oper.build_rule(vector)
    
        antecedent = rule[:cut]
        consequent = rule[cut:]
    
        support, confidence = oper.support_confidence(
            antecedent, consequent, self.transactions)
    
        self.assertEqual(antecedent, antecedent_a)
>       self.assertEqual(consequent, consequent_a)
E       AssertionError: Lists differ: [['0']] != [[0, 0]]
E       
E       First differing element 0:
E       ['0']
E       [0, 0]
E       
E       - [['0']]
E       + [[0, 0]]
niaarm/tests/test_support_confidence.py:48: AssertionError
=========================== short test summary info ============================
FAILED niaarm/tests/test_read_csv.py::TestReadCSVAbalone::test_read_features
FAILED niaarm/tests/test_read_csv.py::TestReadCSVWiki::test_read_features - A...
FAILED niaarm/tests/test_rule_building.py::TestBuildRuleA::test_build_rule - ...
FAILED niaarm/tests/test_rule_building.py::TestBuildRuleA::test_threshold_move
FAILED niaarm/tests/test_shrinkage.py::TestShrinkageA::test_A - AssertionErro...
FAILED niaarm/tests/test_shrinkage.py::TestShrinkageA::test_B - AssertionErro...
FAILED niaarm/tests/test_support_confidence.py::TestSupportConfidence::test_B
FAILED niaarm/tests/test_support_confidence.py::TestSupportConfidence::test_a
========================= 8 failed, 13 passed in 2.83s =========================
>>> ERROR: py3-niaarm: check failed

**Comment by firefly-cpp** [comment]
It is failing on x86 too.  Builds on the other architectures are working well.

**Comment by zStupan** [comment]
That's weird... Did it work with the first release? I don't get why it would work any differently on ARM or 32 bit systems. Maybe it's the same problem with the dataset from the previous issue. I don't know.

**Comment by zStupan** [comment]
I just merged my PR that might fix this issue. I don't have access to an ARM or 32 bit machine to test it out unfortunately.

**Comment by firefly-cpp** [comment]
@zStupan, awesome solution. :)

============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /builddir/build/BUILD/NiaARM-0.1.3
collected 21 items
niaarm/tests/test_coverage.py ..                                         [  9%]
niaarm/tests/test_cut_point.py ...                                       [ 23%]
niaarm/tests/test_read_csv.py ..                                         [ 33%]
niaarm/tests/test_rule_building.py .........                             [ 76%]
niaarm/tests/test_shrinkage.py ...                                       [ 90%]
niaarm/tests/test_support_confidence.py ..                               [100%]
=============================== warnings summary ===============================
../../../../usr/lib64/python3.10/site-packages/numexpr/expressions.py:20
  /usr/lib64/python3.10/site-packages/numexpr/expressions.py:20: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 21 passed, 1 warning in 4.98s =========================

**Comment by zStupan** [comment]
@firefly-cpp Thanks, it was a complete guess :smile: . Closing this issue.
