### ISSUE TITLE
Measure running time of an algorithm

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#26]
Stats class could be extended with this metric. Some research papers also report running time.

**Comment by zStupan** [comment]
The users could just use
```python
import time

start = time.perf_counter()  # or time.time(), but i think perf counter is more accurate
algorithm.run(task)
stop = time.perf_counter()

print(f'Time: {stop - start}s')
```

I think that's a simple enough operation that the users can do it themselves. We could add it to the basic run example.

**Comment by firefly-cpp** [comment]
True. However, it would be nice to have this output also directly in final output with the other stats. It may be optional.
