### ISSUE TITLE
Tests on armhf architecture

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#27]
Several tests are failing on armhf due to the following reason:

**>               unique_categories = sorted(col.unique().tolist(), key=str.lower)
E               TypeError: descriptor 'lower' for 'str' objects doesn't apply to a 'int' object
niaarm/dataset.py:51: TypeError**

**Comment by zStupan** [comment]
there must be an integer somewhere in `col.unique().tolist()` then. I don't understand why this code would behave differently on arm or any other architecture. I'm looking into using qemu to emulate an arm architecture, like a raspberry pi or something, so hopefully i'll be able to reproduce the issue and fix it

**Comment by zStupan** [comment]
Might be fixed in #36
