### ISSUE TITLE
Enable Read the Docs

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#30]

**Comment by firefly-cpp** [comment]
@zStupan, builds are failing on Read the Docs. 

First build: https://readthedocs.org/projects/niaarm/builds/16369876/

I corrected the path and imported niaarm.

Latest build: https://readthedocs.org/projects/niaarm/builds/16370150/

I am not sure, whether we should include all dependencies?

**Comment by zStupan** [comment]
Try now, I think only the path was the problem, I removed the imports

**Comment by firefly-cpp** [comment]
This is the final build: https://readthedocs.org/projects/niaarm/builds/16370219/

**Comment by zStupan** [comment]
It must be the requirements then. I'll add all the dependencies

**Comment by zStupan** [comment]
Ok, now it should work

**Comment by firefly-cpp** [comment]
It works: https://niaarm.readthedocs.io/en/latest/ :)
