### ISSUE TITLE
Test NiaARM package on Windows

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#38]
NiaARM is working well on Linux instances.

@zStupan, Have you already tried to install/run NiaARM on Windows?

**Comment by zStupan** [comment]
I have not, maybe we can add it to the CI workflow. And macOS as well.

**Comment by zStupan** [comment]
The tests are failing on windows: https://github.com/zStupan/NiaARM/runs/5829344958?check_suite_focus=true

**Comment by zStupan** [comment]
It's the same issue as #27. I think pandas just doesn't work properly on 32 bit architectures or something.
