### ISSUE TITLE
Lift metric problem

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#82]
File "/usr/lib/python3.11/site-packages/niaarm/niaarm.py", line 61, in __init__
    raise ValueError(f'Invalid metric(s): {invalid}')
ValueError: Invalid metric(s): lift

**Comment by zStupan** [comment]
This is not a bug, the lift metric cannot be used in the fitness function, as its value is not in range [0, 1]. The only available metrics that can be included in the fitness computation are: https://github.com/firefly-cpp/NiaARM/blob/44f4cca64deb00024827bda4fad5b96be88e4928/niaarm/niaarm.py#L38-L40

**Comment by firefly-cpp** [comment]
Yes. I realized later... Thanks.
