### ISSUE TITLE
Enhance CLI with setup file

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#84]
uARMSolver operates with the setup files where the experiment is defined. This functionality allows easier sharing of experiments. It may be very beneficial to niaarm to inherit this functionality. What do you think, @zStupan?

**Comment by firefly-cpp** [comment]
@zStupan, this seems pretty complex. What do you think? Let's close this issue. (?)

**Comment by zStupan** [comment]
We could use YAML or TOML for the setup file, which would be pretty simple to implement but then it wouldn't be compatible with uARMSolver.

**Comment by firefly-cpp** [comment]
Perfect. I support your idea.
