### ISSUE TITLE
Exceptions and warnings when handling these UCI datasets

### ISSUE THREAD

**Issue by mlaky88** [firefly-cpp/NiaARM#91]
[german.csv](https://github.com/firefly-cpp/NiaARM/files/11542394/german.csv)
[car.csv](https://github.com/firefly-cpp/NiaARM/files/11542401/car.csv)
[buying.csv](https://github.com/firefly-cpp/NiaARM/files/11542402/buying.csv)

**Comment by firefly-cpp** [comment]
Thanks, @mlaky88! 

@zStupan, any ideas?

**Comment by firefly-cpp** [comment]
Thanks, @zStupan. Can we release the new version? Are you planning to add anything else?

**Comment by zStupan** [comment]
@firefly-cpp We can publish a new release.
